# deployes the website at ./website
name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        # with:
        # node-version-file: '.nvmrc'

      - name: Install dependecies and build
        run: |
          cd website/
          npm install
          CI=false npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy Website
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          folder: out # The folder the action should deploy
